/* CREATE TABLE */
/* CREATE TABLE RUNS(RunsID int NOT NULL AUTO_INCREMENT, Test int NOT NULL, ODI int NOT NULL, T20 int NOT NULL, PRIMARY KEY (RunsID)); */

/* CREATE TABLE with foregin key */
/* CREATE TABLE RUNS(RunsID int NOT NULL AUTO_INCREMENT, Test int NOT NULL, ODI int NOT NULL, T20 int NOT NULL, PRIMARY KEY (RunsID)
FOREIGN KEY (PlayerID) REFERENCES PLAYERS(PlayerID)); */

/* ALTER TABLE */
/* ADD COLUMN, DROP COLUMN, MODIFY COLUMN, RENAME COLUMN, RENAME TABLE NAME, */

/* ADD COLUMN */
/* ALTER TABLE table_name ADD column_name datatype; */
/* ALTER TABLE EMPLOYEE ADD PlayerID int AUTO_INCREMENT PRIMARY KEY; */

/* ADD COLUMN AND SET AS FOREIGN KEY */
/* ALTER TABLE RUNS ADD PlayerID int, ADD CONSTRAINT FOREIGN KEY (PlayerID) REFERENCES PLAYERS (PlayerID); */

/* MODIFY COLUMN */
/* ALTER TABLE table_name MODIFY COLUMN column_name datatype;  */
/* ALTER TABLE EMPLOYEE MODIFY COLUMN Emp_Name varchar(150) NOT NULL; */
/* ALTER TABLE RUNS MODIFY COLUMN PlayerID int NOT NULL; */
/* ALTER TABLE RUNS MODIFY COLUMN PlayerID int UNIQUE; */

/* /RENAME TABLE */
/* ALTER TABLE EMPLOYEE RENAME TO PLAYERS; */

/* RENAME COLUMN */
/* ALTER TABLE PLAYERS RENAME COLUMN Emp_Name TO Name; */

/* TRUNCATE TABLE  */
/* TRUNCATE TABLE table_name */
/* drop every records, but retains the table structure */

/* DROP COLUMN */
/* DROP TABLE table_name */

