/* DELETE */
/* DELETE FROM EMPLOYEE WHERE Jersey = 17; */

/* Deletes all records */
/* DELETE FROM EMPLOYEE; */

/* INSERT */
/* INSERT INTO PLAYERS VALUES(10,'SACHIN','MALE',"MUMBAI","INDIA",46,NULL); */
/* OR */
/* INSERT INTO PLAYERS(Jersey,Name,Gender,City,Country,Age,PlayerID) VALUES(12,'BUTLER','MALE',"LORDS","ENGLAND",37,NULL); */

INSERT INTO RUNS VALUES(NULL,1362,570,70,1);